import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { montserrat } from "./fonts";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
     <body
  className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} bg-base-100 text-base-content font-sans antialiased`}
>
  {children}
</body>
    </html>
  );
}
